name: Trigger auto deployment for summa-container-007

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/summa-container-007-AutoDeployTrigger-424660f0-1014-4b19-b378-cd49a957c51e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SUMMACONTAINER007_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SUMMACONTAINER007_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUMMACONTAINER007_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}github/workflows/docker-publish.yml
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SUMMACONTAINER007_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SUMMACONTAINER007_REGISTRY_PASSWORD }}
          containerAppName: summa-container-007
          resourceGroup: th-resource-demo
          imageToBuild: joseph24x7/summa-container-007:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


